# yaml-language-server: $schema=https://json.schemastore.org/github-action.json

name: 'Benedi.kt'
author: 'The diKTat Team'
description: 'A GitHub Action to check your code with diKTat'

# Note: when inverting the default values of boolean flags, be sure to also
# invert the values they're compared to, i.e. if a certain flag is `true` by
# default, then it should be compared with `false`, because `false` is the only
# value which users of our action can explicitly set. Cases when a flag is
# merely inset (i.e. is not equal to either `true` or `false`) are quite common.
inputs:
  config:
    description: >
      The location of the YAML configuration file. By default,
      diktat-analysis.yml in the current directory is used.
    default: 'diktat-analysis.yml'
    required: false
  reporter:
    description: >
      The reporter to use, one of: "plain", "plain?group_by_file", "json",
      "sarif" (the default), "checkstyle", "html".
    default: 'sarif'
    required: false
  input-paths:
    description: >
      One or more patterns which indicate the files or directories to check.
      Use a multiline string to specify multiple inputs.

      If an input is a path to a file, it is passed to diKTat as-is.

      If an input is a path to a directory, the directory is recursively
      traversed, and all *.kt and *.kts files are passed to diKTat.

      If an input is an Ant-like path pattern (such as "**/*.kt"), diKTat
      expands it into the list of files that match the path pattern. Path
      patterns may be negated, e. g.: "!src/**/*Test.kt" or
      "!src/**/generated/**".
    required: false
  java-distribution:
    description: >
      The Java distribution. See the list of supported distributions at
      <https://github.com/actions/setup-java/blob/main/README.md#supported-distributions>.
      The default is "temurin".

      Note that setting just this property in order to use a custom JDK is not
      sufficient: please set "java-version", too.
    default: 'temurin'
    required: false
  java-version:
    description: >
      The Java version to set up. Takes a whole or semver Java version. See
      examples of supported syntax at
      <https://github.com/actions/setup-java/blob/main/README.md#supported-version-syntax>.
    required: false
  color:
    description: >
      Colorize the output
    default: ${{ true }}
    required: false
  debug:
    description: >
      Whether debug logging should be enabled
    default: ${{ false }}
    required: false
  relative-paths:
    description: >
      Relativize file paths with respect to the working directory (if false,
      absolute file paths get reported)
    default: ${{ true }}
    required: false
  fail-on-error:
    description: >
      Whether linter errors are considered fatal (the default is true)
    default: ${{ true }}
    required: false

outputs:
  exit-code:
    description: "The exit code of diKTat"
    value: ${{ steps.diktat.outputs.exit-code }}

runs:
  using: "composite"
  steps:
    - id: setup-java
      if: ${{ inputs.java-version != null }}
      uses: actions/setup-java@v3
      with:
        distribution: '${{ inputs.java-distribution }}'
        java-version: ${{ inputs.java-version }}

    - run: echo '${{ github.action_path }}/bin' >>${GITHUB_PATH}
      shell: bash

      # GitHub seems to set `-e` internally, so don't fail immediately if diKTat
      # returns a non-zero exit code but store the exit code in a variable for
      # further processing.
      #
      # This step is always successful but records the exit code in the
      # `steps.diktat.outputs.exit-code` variable.
    - id: diktat
      run: |
        DIKTAT_ARGS=('--config=${{ inputs.config }}')
        DIKTAT_ARGS=('--reporter=${{ inputs.reporter }}')
        if [[ '${{ inputs.color }}' != 'false' ]]
        then
          DIKTAT_ARGS+=('--color')
        fi
        if [[ '${{ inputs.debug }}' == 'true' ]]
        then
          DIKTAT_ARGS+=('--debug')
        fi
        if [[ '${{ inputs.relative-paths }}' != 'false' ]]
        then
          DIKTAT_ARGS+=('--relative')
        fi

        set -o pipefail
        IFS=$'\n'
        INPUT_PATHS=(${{ inputs.input-paths }})
        { diktat --no-download-progress --verbose "${DIKTAT_ARGS[@]}" "${INPUT_PATHS[@]}" | tee diktat.log; } && exit_code=$? || exit_code=$?
        echo "::set-output name=summary-line::$(tail -n1 diktat.log 2>/dev/null)"
        rm -f diktat.log
        echo "::set-output name=exit-code::${exit_code}"
      env:
        GITHUB_TOKEN: ${{ github.token }}
      shell: bash

      # Creates a summary report and fails the job if necessary.
      #
      # If `diktat` exited with code 1 (linter errors), return 0 or 1 depending
      # on the value of the `fail-on-error` flag. If the exit code is 2 or
      # greater, return it as-is, ignoring the flag.
      #
      # Note: BSD `awk` apparently doesn't understand `\\s`, that's why we're
      # splitting on `: *` (a colon followed by a zero or more space characters).
    - id: diktat-summary
      if: ${{ always() }}
      run: |
        if (( ${{ steps.diktat.outputs.exit-code }} == 0 ))
        then
          status_icon=':heavy_check_mark:'
          message='completed successfully'
        else
          status_icon=':x:'
          message='exited with code **${{ steps.diktat.outputs.exit-code }}**'
        fi

        diktat='[_diKTat_](https://github.com/saveourtool/diktat)'

        echo "${status_icon} ${diktat} ${message}" >>${GITHUB_STEP_SUMMARY}

        if (( ${{ steps.diktat.outputs.exit-code }} != 0 ))
        then
          echo '```console' >>${GITHUB_STEP_SUMMARY}
          echo "${{ steps.diktat.outputs.summary-line }}" >>${GITHUB_STEP_SUMMARY}
          echo '```' >>${GITHUB_STEP_SUMMARY}
        fi

        if (( ${{ steps.diktat.outputs.exit-code }} <= 1 ))
        then
          diktat --version | awk '{ split($0, versions, ": *"); print " - _" versions[1] "_: **" versions[2] "**" }' >>${GITHUB_STEP_SUMMARY}
        fi

        if (( ${{ steps.diktat.outputs.exit-code }} != 1 ))
        then
          exit ${{ steps.diktat.outputs.exit-code }}
        elif [[ '${{ inputs.fail-on-error }}' != 'false' ]]
        then
          exit 1
        fi
      shell: bash

      # We only need this step to run if diKTat failed to download external
      # files (3), and we need to publish the logs.
    - uses: actions/upload-artifact@v3
      if: ${{ failure() && steps.diktat.outputs.exit-code == 3 }}
      with:
        name: download-logs
        path: |
          ${{ github.action_path }}/bin/*-download.log
        if-no-files-found: ignore
        retention-days: 1

      # When in SARIF reporting mode, upload SARIF reports to GitHub.
    - id: upload-sarif
      if: ${{ always() && steps.diktat.outputs.exit-code == 1 && inputs.reporter == 'sarif' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ github.workspace }}

      # Alternatively, when in Checkstyle reporting mode, upload Checkstyle XML
      # using `reviewdog`.
      #
      # `reviewdog` doesn't play well with manual runs (`workflow_dispatch`):
      # it fails with
      #
      # post failed for %s: failed to create check: POST https://api.github.com/repos/%s/%s/check-runs: 422 No commit found for SHA:  []
    - id: reviewdog-install
      if: ${{ always() && steps.diktat.outputs.exit-code == 1 && inputs.reporter == 'checkstyle' && github.event_name != 'workflow_dispatch' }}
      uses: reviewdog/action-setup@v1

    - id: reviewdog
      if: ${{ always() && steps.diktat.outputs.exit-code == 1 && inputs.reporter == 'checkstyle' && github.event_name != 'workflow_dispatch' }}
      run: |
        if [[ '${{ github.event_name }}' == 'pull_request' ]]
        then
          reviewdog_reporter='github-pr-check'
        else
          reviewdog_reporter='github-check'
        fi

        reviewdog -f=checkstyle -fail-on-error=false -level=info -name='diKTat errors reported by reviewdog' -reporter="${reviewdog_reporter}" <checkstyle-report.xml
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
      shell: bash

branding:
  icon: 'check-circle'
  color: 'purple'
