name: GitHub Pages Publish

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Publish GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Remove irrelevant files
        run: |
          rm -rf .idea/ bin/ .editorconfig .gitignore .gitattributes CODE_OF_CONDUCT.md LICENSE *.yml
        shell: bash

      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to
      # html and publish to gh-pages branch.
      - name: asciidoctor-ghpages
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: true
          # asciidoctor_params: --attribute=nofooter
          asciidoctor_params: --attribute=allow-uri-read
          # adoc_file_ext: .ascii # default is .adoc
          # source_dir: docs/ # default is .
          # slides_build: true
          # pre_build:
          # post_build:
