name: Create a binary distribution (full)

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  dist:
    name: Binary distribution (full)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - id: filenames
        run: |
          echo "diktat-cli-tar=diktat-cli-${{ inputs.release-version }}-full.tar"    >>"${GITHUB_OUTPUT}"
          echo "diktat-cli-tgz=diktat-cli-${{ inputs.release-version }}-full.tar.gz" >>"${GITHUB_OUTPUT}"
          echo "diktat-cli-zip=diktat-cli-${{ inputs.release-version }}-full.zip"    >>"${GITHUB_OUTPUT}"
        shell: bash

      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Download dependencies
        run: |
          bin/diktat --no-download-progress -V
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash

      - run: |
          tar cf '${{ steps.filenames.outputs.diktat-cli-tar }}' --exclude-backups --exclude-vcs --exclude-vcs-ignore --exclude='*.bat' --exclude='*.cmd' -C bin .
          gzip -9 '${{ steps.filenames.outputs.diktat-cli-tar }}'
          zip -jrX9 -Z bzip2 '${{ steps.filenames.outputs.diktat-cli-zip }}' bin
        shell: bash

        # Upload a .tar.gz artifact, except when this is a release.
      - name: Upload ${{ steps.filenames.outputs.diktat-cli-tgz }}
        if: ${{ github.ref_type == 'branch' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.filenames.outputs.diktat-cli-tgz }}
          path: ${{ steps.filenames.outputs.diktat-cli-tgz }}
          if-no-files-found: error
          retention-days: 1

        # Upload a .zip artifact, except when this is a release.
      - name: Upload ${{ steps.filenames.outputs.diktat-cli-zip }}
        if: ${{ github.ref_type == 'branch' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.filenames.outputs.diktat-cli-zip }}
          path: ${{ steps.filenames.outputs.diktat-cli-zip }}
          if-no-files-found: error
          retention-days: 1
