name: Create a binary distribution (thin)

on:
  workflow_call:

jobs:
  dist:
    name: Binary distribution (thin)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "RELEASE_VERSION=${GITHUB_REF#'refs/tags/v'}"
        shell: bash
