name: Create a binary distribution (thin)

on:
  workflow_call:

jobs:
  dist:
    name: Binary distribution (thin)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "GITHUB_HEAD_REF_NAME=${GITHUB_HEAD_REF_NAME}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "GITHUB_REF_TYPE=${GITHUB_REF_TYPE}"
          echo "GITHUB_SHA=${GITHUB_SHA}"
          echo "RELEASE_VERSION=${GITHUB_REF#'refs/tags/v'}"
        shell: bash
