name: Create a binary distribution (thin)

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  dist:
    name: Binary distribution (thin)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "RELEASE_VERSION=${{ inputs.release-version }}"
        shell: bash
