name: Move the Marketplace tag

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  dist:
    name: Move the Marketplace tag
    # See https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo "RELEASE_VERSION=${{ inputs.release-version }}"
        shell: bash
