name: Move the Marketplace tag

on:
  workflow_call:

jobs:
  dist:
    name: Move the Marketplace tag
    if: env.REF_TYPE == 'branch'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
