name: Move the Marketplace tag

on:
  workflow_call:
    inputs:
      release-version:
        required: true
        type: string

jobs:
  dist:
    name: Move the Marketplace tag
    # See https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
    if: github.ref_type == 'tag'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: tag
        name: Tag name
        run: |
          VERSION_MAJOR="$(echo '${{ inputs.release-version }}' | sed -nE '/^([0-9]+)\.[^\.]+.*$/s//\1/p')"
          echo "name=v${VERSION_MAJOR}" >>"${GITHUB_OUTPUT}"
        shell: bash

        # The tag may not exist yet, so continue on error.
      - name: Delete local tag
        run: |
          git tag -d '${{ steps.tag.outputs.name }}'
        continue-on-error: true
        shell: bash

        # The tag may not exist yet, so continue on error.
      - name: Delete remote tag
        run: |
          git push --delete origin '${{ steps.tag.outputs.name }}'
        continue-on-error: true
        shell: bash

      - name: Create local tag
        run: |
          git tag '${{ steps.tag.outputs.name }}'
        shell: bash

      - name: Push local tag
        run: |
          git push origin '${{ steps.tag.outputs.name }}'
        shell: bash
