name: Create a new release (new)

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*'
      # Ignore simple tags which are just "aliases" used by the Marketplace.
      - '!v1'
      - '!v2'
      - '!v3'
      - '!v4'
      - '!v5'
      - '!v6'
      - '!v7'
      - '!v8'
      - '!v9'

jobs:
  version:
    name: Calculate the release version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

        # Infer the release version. Assumes that tags are named `vX.Y.Z`.
      - id: version
        run: |
          if [[ "${GITHUB_REF_TYPE}" == 'branch' ]]
          then
            RELEASE_VERSION="${GITHUB_SHA}"
          else
            RELEASE_VERSION="${GITHUB_REF#'refs/tags/v'}"
            RELEASE_VERSION="${RELEASE_VERSION//'/'/_}"
          fi

          echo "GITHUB_REF=${GITHUB_REF}"
          echo "GITHUB_REF_NAME=${GITHUB_REF_NAME}"
          echo "GITHUB_BASE_REF=${GITHUB_BASE_REF}"
          echo "GITHUB_HEAD_REF=${GITHUB_HEAD_REF}"
          echo "RELEASE_VERSION=${RELEASE_VERSION}"
          echo "release-version=${RELEASE_VERSION}" >>${GITHUB_OUTPUT}
        shell: bash
    outputs:
      release-version: ${{ steps.version.outputs.release-version }}

  bindist-thin:
    name: Binary distribution (thin)
    needs: [ version ]
    uses: ./.github/workflows/bindist-thin.yml
    with:
      release-version: ${{ needs.version.outputs.release-version }}
    secrets: inherit

  bindist-full:
    name: Binary distribution (full)
    needs: [ version, bindist-thin ]
    uses: ./.github/workflows/bindist-full.yml
    with:
      release-version: ${{ needs.version.outputs.release-version }}
    secrets: inherit

  move-tag:
    name: Move the Marketplace tag
    needs: [ version, bindist-thin, bindist-full ]
    uses: ./.github/workflows/move-marketplace-tag.yml
    with:
      release-version: ${{ needs.version.outputs.release-version }}
    secrets: inherit
