name: Create a new release (new)

on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*.*'
      # Ignore simple tags which are just "aliases" used by the Marketplace.
      - '!v1'
      - '!v2'
      - '!v3'
      - '!v4'
      - '!v5'
      - '!v6'
      - '!v7'
      - '!v8'
      - '!v9'

jobs:
  bindist-thin:
    uses: ./.github/workflows/bindist-thin.yml
    secrets: inherit

  bindist-full:
    uses: ./.github/workflows/bindist-full.yml
    secrets: inherit

  move-tag:
    uses: ./.github/workflows/move-marketplace-tag.yml
    secrets: inherit
